USE [FairManagement_DB]
GO

/****** Object:  Table [dbo].[ZoneType_T]    Script Date: 05/27/2015 21:56:41 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ZoneType_T](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ZoneName] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_ZoneType_T] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


